apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryservice-deployment
  labels:
    app: discoveryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discoveryservice
  template:
    metadata:
      labels:
        app: discoveryservice
    spec:
      containers:
        - name: discoveryservice
          image: alearandoesp/discoveryservice:1.0.0
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 15
          env:
            - name: SERVER_PORT
              value: "8761"
            - name: DISCOVERY_TAG
              valueFrom:
                configMapKeyRef:
                  name: image-versions-configmap
                  key: DISCOVERY_TAG