apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  labels:
    app: userservice
spec:
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
