apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
data:
  USER_DB_NAME: user_service_db
  AGENDA_DB_NAME: agenda_service_db
  REACT_APP_API_BASE_URL: http://gatewayservice:8080/api/v1
