apiVersion: v1
kind: Service
metadata:
  name: discoveryservice-service
  labels:
    app: discoveryservice
spec:
  selector:
    app: discoveryservice
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
