apiVersion: v1
kind: Service
metadata:
  name: gatewayservice-service
  labels:
    app: gatewayservice
spec:
  selector:
    app: gatewayservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
